config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :user_profiles, only: [:edit, :create, :update, :destroy]

  get    'users/search'       => 'users#search',       as: :users_search
  post   'users/:id/friend'   => 'users#friend',       as: :friend
  delete 'users/:id/unfriend' => 'users#unfriend',     as: :unfriend
  get    'users/:id/profile'  => 'user_profiles#edit', as: :users_edit_profile
  get    'users/:id'          => 'users#show',         as: :user

  get 'movies/search'         => 'movies#search',      as: :movies_search
  get 'movies/:id'            => 'movies#show',        as: :movie

  resources :ratings
  resources :recommendations

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.includes(:friends).find(current_user.id)

    @movie = MovieFinder.new.find_movie(params[:id])
    @rating = (
      current_user.ratings.find_by(rottentomatoes_id: params[:id]) ||
      Rating.new(rottentomatoes_id: params[:id], rater: current_user)
    )
  end

  def search
    if request.GET[:title]
      @movie_dicts = MovieFinder.new.search(request.GET[:title])
    else
      @movie_dicts = []
    end
  end
end

app/views/movies/_movie_item.html.erb
<tr><td><%= link_to movie_item[:title], movie_path(movie_item[:id]) %></td></tr>

app/views/movies/_rating_form.html.erb
<%= simple_form_for @rating do |f| %>
    <% if @rating.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

            <ul>
                <% @rating.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.input :rottentomatoes_id, as: :hidden %>
    <%= f.input :rater_id, as: :hidden %>
    <%= f.collection_radio_buttons :rating,
          [
            [0, '0'],
            [1, '1'],
            [2, '2'],
            [3, '3'],
            [4, '4'],
            [5, '5'],
            [6, '6'],
            [7, '7'],
            [8, '8'],
            [9, '9'],
            [10, '10']
          ],
          :first,
          :last
    %>
    <%= f.button :submit %>
<% end %>

app/views/movies/_recommendation_form.html.erb
<h2>Recommend to:</h2>

<%= form_tag recommendations_path do %>
    <table class="table table-bordered">
        <% @user.friends.each do |friend| %>
            <tr>
                <td><%= check_box_tag "friend-#{friend.id}", friend.id %></td>
                <td><%= label_tag "friend-#{friend.id}", friend.email %></td>
            </tr>
        <% end %>
    </table>
    <%= hidden_field_tag 'rottentomatoes_id', params[:id] %>
    <%= submit_tag 'Submit', class: 'btn btn-success' %>
<% end %>

app/views/movies/search.html.erb
<h1>Search</h1>
<%= form_tag movies_search_path, method: :get do %>
    <%= text_field_tag 'title' %>
    <%= submit_tag 'Submit' %>
<% end %>

<h1>Movies</h1>
<table class="table table-bordered">
    <%= render partial: 'movie_item', collection: @movie_dicts %>
</table>

app/views/movies/show.html.erb
<h1><%= @movie.title %> (<%= @movie.mpaa_rating %>) &mdash; <%= @movie.year %></h1>

<table class="table table-bordered">
    <tr>
        <th colspan="2">Ratings</th>
    </tr>
    <tr>
        <td>Critic&apos;s Score</td>
        <td><%= @movie.critics_score %></td>
    </tr>
    <tr>
        <td>Audience Score</td>
        <td><%= @movie.audience_score %></td>
    </tr>
</table>

<h2>Your Rating</h2>
<%= render 'rating_form' %>
<%= render 'recommendation_form' %>