config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :user_profiles, only: [:edit, :create, :update, :destroy]

  get    'users/search'       => 'users#search',       as: :users_search
  post   'users/:id/friend'   => 'users#friend',       as: :friend
  delete 'users/:id/unfriend' => 'users#unfriend',     as: :unfriend
  get    'users/:id/profile'  => 'user_profiles#edit', as: :users_edit_profile
  get    'users/:id'          => 'users#show',         as: :user

  get 'movies/search'         => 'movies#search',      as: :movies_search
  get 'movies/:id'            => 'movies#show',        as: :movie

  resources :ratings
  resources :recommendations

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable, :confirmable

  has_one  :user_profile

  has_many :friendships
  has_many :friends, through: :friendships

  has_many :ratings, foreign_key: :rater_id

  has_many :recommendations, class_name: 'Recommendation', foreign_key: 'recommendee_id'
  has_many :recommended,     class_name: 'Recommendation', foreign_key: 'recommender_id'

  delegate :name, :private, :show_ratings,
    to: :user_profile

  before_create :send_email

  def currently_friends_with?(user)
    Friendship.where(user: self, friend: user, pending: false).length > 0
  end

  def friend_request_sent_to?(user)
    Friendship.where(user: user, friend: self, pending: true).length > 0
  end

  def friend_request_received_from?(user)
    Friendship.where(user: self, friend: user, pending: true).length > 0
  end

  def send_friend_request_to(user)
    Friendship.create(user: user, friend: self, pending: true)
  end

  def accept_friend_request_from(user)
    friendships = Friendship.where(user: self, friend: user, pending: true)
    return if friendships.length == 0

    my_friendship = friendships[0]
    my_friendship.pending = false
    my_friendship.save

    their_friendship = Friendship.create(user: user, friend: self, pending: false)
    their_friendship.save
  end

  def unfriend(user)
    Friendship.where(user: user, friend: self).destroy_all
    Friendship.where(user: self, friend: user).destroy_all
  end

  private

  def send_email
    NotificationMailer.new_user(self).deliver
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:search]
  before_action :authenticate_user!

  def show
  end

  def friend
    if current_user == @user
      flash[:alert] = 'You cannot friend yourself.'
      return redirect_to user_path
    end

    if current_user.friend_request_received_from?(@user)
      current_user.accept_friend_request_from(@user)
      flash[:notice] = 'User successfully friended.'
    elsif !current_user.currently_friends_with?(@user) && !current_user.friend_request_sent_to?(@user)
      current_user.send_friend_request_to(@user)
      flash[:notice] = 'Friend request sent.'
    else
      flash[:notice] = 'Friend request sent.'
    end

    redirect_to user_path(@user)
  end

  def unfriend
    current_user.unfriend(@user)

    flash[:alert] = 'User successfully unfriended.'
    redirect_to user_path(@user)
  end

  def search
    email = request.GET[:email]
    @user = User.find_by(email: email)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_current_friendship.html.erb
<tr><td><%= link_to current_friendship.friend_email, current_friendship.friend %></td></tr>

app/views/users/_friend_profile.html.erb
<table class="table table-bordered">
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>

    <tr>
        <td><%= @user.user_profile && @user.name %></td>
        <td><%= @user.email %></td>
    </tr>
</table>

<% if current_user.currently_friends_with?(@user) %>
    <%= link_to 'Unfriend', unfriend_path(@user), method: :delete, class: 'btn btn-danger' %>
<% else %>
    <p>This user is currently pending your approval.</p>
    <%= link_to 'Friend', friend_path(@user), method: :post, class: 'btn btn-success' %>
<% end %>

<% if @user.user_profile && @user.show_ratings %>
    <%= render partial: 'ratings' %>
<% end %>

<h1>Friends</h1>
<% @user.friendships.current.each do |friendship| %>
    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Email</th>
        </tr>

        <tr>
            <td><%= link_to friendship.friend.user_profile && friendship.friend.name || '', friendship.friend %></td>
            <td><%= link_to friendship.friend_email, friendship.friend %></td>
        </tr>
    </table>
<% end %>

app/views/users/_pending_friendship.html.erb
<tr><td><%= link_to pending_friendship.friend_email, pending_friendship.friend %></td></tr>

app/views/users/_pending_friendships.html.erb
<h1>Pending Friends</h1>
<table class="table table-bordered">
    <%= render partial: 'pending_friendship', collection: @user.friendships.pending %>
</table>

app/views/users/_private.html.erb
<h1>Private</h1>

<% if current_user.currently_friends_with?(@user) %>
    <%= link_to 'Unfriend', unfriend_path(@user), method: :delete, class: 'btn btn-danger' %>
<% else %>
    <%= link_to 'Friend', friend_path(@user), method: :post, class: 'btn btn-success' %>
<% end %>

app/views/users/_ratings.html.erb
<h1>Ratings</h1>
<table class="table table-bordered">
    <tr>
        <th>Movie</th>
        <th>Rating</th>
    </tr>
    <%= render partial: 'rating', collection: @user.ratings %>
</table>

app/views/users/_recommendation.html.erb
<tr>
    <td class="rottentomatoes">
        <%= link_to recommendation.movie_title, movie_path(recommendation.movie.rottentomatoes_id) %>
    </td>
    <td class="recommender">
        <%= link_to recommendation.recommender.email, recommendation.recommender %>
    </td>
    <td class="delete">
        <%= link_to 'Delete', recommendation, method: :delete %>
    </td>
</tr>

app/views/users/_recommendations.html.erb
<h1>Recommended For You</h1>
<table class="table table-bordered">
    <tr>
        <th>Movie</th>
        <th>Recommended By</th>
        <th></th>
    </tr>
    <%= render partial: 'recommendation', collection: @user.recommendations %>
</table>

app/views/users/_recommended.html.erb
<h1>You Recommended</h1>
<table class="table table-bordered">
    <tr>
        <th>Movie</th>
        <th>Recommended To</th>
        <th></th>
    </tr>
    <%= render partial: 'recommended_movie', collection: @user.recommended %>
</table>

app/views/users/_recommended_movie.html.erb
<tr>
    <td class="rottentomatoes">
        <%= link_to recommended_movie.movie_title, movie_path(recommended_movie.movie.rottentomatoes_id) %>
    </td>
    <td class="recommendee">
        <%= link_to recommended_movie.recommendee.email, recommended_movie.recommendee %>
    </td>
    <td class="delete">
        <%= link_to 'Delete', recommended_movie, method: :delete %>
    </td>
</tr>

app/views/users/_self_profile.html.erb
<%= render partial: 'current_friendships' %>
<%= render partial: 'pending_friendships' %>
<%= render partial: 'ratings' %>
<%= render partial: 'recommendations' %>
<%= render partial: 'recommended' %>

app/views/users/search.html.erb
<h1>Search</h1>
<%= form_tag users_search_path, method: :get do %>
    <%= text_field_tag 'email' %>
    <%= submit_tag 'Submit' %>
<% end %>

<h1>Users</h1>
<table class="table table-bordered">
    <% if @user %>
        <tr><td><%= link_to @user.email, @user %></td></tr>
    <% end %>
</table>

app/views/users/show.html.erb
<% if current_user == @user %>
    <%= render partial: 'self_profile' %>
<% elsif current_user.friends.include?(@user) %>
    <%= render partial: 'friend_profile' %>
<% elsif @user.user_profile && @user.private %>
    <%= render partial: 'private' %>
<% else %>
    <%= render partial: 'profile' %>
<% end %>

app/views/users/unfriend.html.erb
<h1>Users#unfriend</h1>
<p>Find me in app/views/users/unfriend.html.erb</p>