config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :user_profiles, only: [:edit, :create, :update, :destroy]

  get    'users/search'       => 'users#search',       as: :users_search
  post   'users/:id/friend'   => 'users#friend',       as: :friend
  delete 'users/:id/unfriend' => 'users#unfriend',     as: :unfriend
  get    'users/:id/profile'  => 'user_profiles#edit', as: :users_edit_profile
  get    'users/:id'          => 'users#show',         as: :user

  get 'movies/search'         => 'movies#search',      as: :movies_search
  get 'movies/:id'            => 'movies#show',        as: :movie

  resources :ratings
  resources :recommendations

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'Movie Tell', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <%= render 'layouts/navigation_links' %>
            </ul>

            <div class="nav navbar-nav navbar-right">
                <% if !current_user %>
                    <%= button_to 'Sign In/Sign Up', new_user_session_path, class: 'btn btn-success' %>
                <% else %>
                    <%= button_to "Sign Out (#{current_user.email})",
                          destroy_user_session_path,
                          method: :delete,
                          class: 'btn btn-danger' %>
                <% end %>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Search Users', users_search_path %></li>
<li><%= link_to 'Search Movies', movies_search_path %></li>
<% if current_user %>
    <li><%= link_to 'Profile', users_edit_profile_path(current_user) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><%= content_for?(:title) ? yield(:title) : "Movie Tell" %></title>
        <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Movie Tell" %>">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>

    <body>
        <header>
            <%= render 'layouts/navigation' %>
        </header>
        <main role="main" class="container">
            <%= render 'layouts/messages' %>
            <%= yield %>
        </main>
    </body>
</html>